# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-23 13:01
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContigsFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=2048)),
                ('file_index', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('remember', models.BooleanField()),
                ('reference_fname', models.CharField(blank=True, max_length=2048, null=True)),
                ('genes_fname', models.CharField(blank=True, max_length=2048, null=True)),
                ('operons_fname', models.CharField(blank=True, max_length=2048, null=True)),
                ('dirname', autoslug.fields.AutoSlugField(editable=False, populate_from=b'name')),
            ],
        ),
        migrations.CreateModel(
            name='QuastSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=255, unique=True)),
                ('link', models.CharField(blank=True, max_length=2048, null=True)),
                ('min_contig', models.IntegerField(blank=True, null=True)),
                ('scaffolds', models.BooleanField(default=False)),
                ('eukaryotic', models.BooleanField(default=False)),
                ('estimated_ref_size', models.IntegerField(blank=True, null=True)),
                ('find_genes', models.BooleanField(default=False)),
                ('caption', models.CharField(blank=True, max_length=1024, null=True)),
                ('comment', models.TextField(blank=True, max_length=200000, null=True)),
                ('task_id', models.CharField(blank=True, max_length=1024, null=True)),
                ('submitted', models.BooleanField(default=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuastSession_ContigsFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contigs_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quast_app.ContigsFile')),
                ('quast_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quast_app.QuastSession')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(blank=True, max_length=256, null=True)),
                ('input_dirname', models.CharField(blank=True, max_length=256, null=True)),
                ('min_contig', models.IntegerField(default=500)),
                ('scaffolds', models.BooleanField(default=False)),
                ('eukaryotic', models.BooleanField(default=False)),
                ('estimated_ref_size', models.IntegerField(blank=True, null=True)),
                ('find_genes', models.BooleanField(default=False)),
                ('default_data_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quast_app.DataSet')),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=255, unique=True)),
                ('input_dirname', models.CharField(max_length=2048)),
                ('min_contig', models.IntegerField(default=500)),
                ('scaffolds', models.BooleanField(default=False)),
                ('eukaryotic', models.BooleanField(default=False)),
                ('estimated_ref_size', models.IntegerField(blank=True, null=True)),
                ('find_genes', models.BooleanField(default=False)),
                ('default_data_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quast_app.DataSet')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quast_app.User')),
            ],
        ),
        migrations.AddField(
            model_name='quastsession',
            name='contigs_files',
            field=models.ManyToManyField(through='quast_app.QuastSession_ContigsFile', to='quast_app.ContigsFile'),
        ),
        migrations.AddField(
            model_name='quastsession',
            name='data_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quast_app.DataSet'),
        ),
        migrations.AddField(
            model_name='quastsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quast_app.User'),
        ),
        migrations.AddField(
            model_name='quastsession',
            name='user_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quast_app.UserSession'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quast_app.User'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='user_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quast_app.UserSession'),
        ),
    ]
