#!/bin/csh -f
#
# Find exact tandem repeats in specified file involving an
# exact duplicate of at least the specified length

set filename = $1
set matchlen = $2

set bindir = /Users/vladsaveliev/Dropbox/bio/quast/quast-website/quast-1.3/libs/MUMmer3.23-osx
set scriptdir = /Users/vladsaveliev/Dropbox/bio/quast/quast-website/quast-1.3/libs/MUMmer3.23-osx/scripts

if  ($filename == '' || $matchlen == '')  then
    echo "USAGE:  $0 <file> <min-match-len>"
    exit -1
endif

echo "Finding matches"
$bindir/repeat-match -t -n $matchlen $filename | tail +3 > $$.tmp.matches
if  ($status != 0)  exit -1

echo "Tandem repeats"
sort -k1n -k2n $$.tmp.matches | awk -f $scriptdir/tandem-repeat.awk
rm -f $$.tmp.matches
